name: Preview build

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to build'
        required: true
        type: string
      environment:
        description: 'Target environment'
        type: choice
        options:
          - DEV
          - INT
          - PREPROD
        required: true

jobs:
  build-image-preview:
    uses: homelab994/gh-newops/.github/workflows/build-push-docker-preview.yml@develop
    with:
      pr_number: ${{ inputs.pr_number }}
      artifact-name: 'gh-simple-spring'
    secrets: inherit

  deploy-preview:
    needs: build-image-preview
    uses: homelab994/gh-newops/.github/workflows/deploy-k8s-preview.yml@develop
    with:
      artifact-name: 'gh-simple-spring'
      release-version: ${{ needs.build-image.outputs.preview-version }}
      environment: ${{ inputs.environment }}
    secrets: inherit
